### ISSUE TITLE
Fork 2.60.1: Abnormal RAM usage

### ISSUE THREAD

**Issue by max-vyshnevskyi** [ForkIssues/Tracker#2512]
After updating to version 2.60.1 (I’m not sure what the previous version was), the app started consuming an enormous amount of RAM right after launch. Memory usage kept climbing past 100 GB, relying on disk caches until the disk filled up, causing severe system lag. I had to force quit the app each time. The issue reproduced consistently on every launch.

It might be related to the automatic repository scan. Previously, my user’s root folder was selected as Source Code Folder. After changing it to a specific folder inside Documents folder, the issue disappeared.

MacOS 15.7, M3 Pro

**Comment by DanPristupov** [comment]
Thank you for reporting the problem. I'm investigating it.

**Comment by DanPristupov** [comment]
We just released Fork 2.60.2 hotfix. Please check for updates.

**Comment by max-vyshnevskyi** [comment]
Thank you for fixing it so quickly. Issue is not reporoducible anymore.

**Comment by xuhaoranLeo** [comment]
Issue: v2.60.2 memory still leaks until OoK

<img width="573" height="54" alt="Image" src="https://github.com/user-attachments/assets/e54543f2-f9fe-44a5-8bb4-d6e57c4730c8" />

@max-vyshnevskyi

**Comment by Rspoon3** [comment]
I’m also still getting this behavior on 2.60.2.

<img width="591" height="479" alt="Image" src="https://github.com/user-attachments/assets/55bddb77-7629-49c5-b45d-e5295255cf18" />

**Comment by DanPristupov** [comment]
@Rspoon3 can you show output of `head -n 3 ~/Library/Application\ Support/com.DanPristupov.Fork/repositories.toml`, please?

**Comment by max-vyshnevskyi** [comment]
It looks like setting my user’s root folder as the Source Code Folder didn’t work correctly. The app shows a warning icon, but doesn’t provide any details. It’s possible the folder selection failed for some reason, which might explain why the issue isn’t reproducible now, I didn’t notice this yesterday.

<img width="565" height="183" alt="Image" src="https://github.com/user-attachments/assets/c64163a4-8a00-4dc1-989b-b135e296d41a" />

@xuhaoranLeo @Rspoon3 try changing your Source Code Folder as a temporary workaround.

I’m reopening this issue since users are still experiencing the problem.

**Comment by DanPristupov** [comment]
> The app shows a warning icon, but doesn’t provide any details.

Check the tooltip over the warning icon.

**Comment by DanPristupov** [comment]
For the users who still have a problem. I made a build with additional logging. https://cdn.fork.dev/prerelease/Fork-2.60.20.dmg
Can you run it, reproduce the problem and then send me the log file, please? The log is located at `~/Library/Logs/Fork.log`

**Comment by max-vyshnevskyi** [comment]
> > The app shows a warning icon, but doesn’t provide any details.
> 
> Check the tooltip over the warning icon.

ah, you’re right, there’s a tooltip. I just needed to keep my mouse over the icon a bit longer 😅

<img width="449" height="92" alt="Image" src="https://github.com/user-attachments/assets/0f313bcd-b38b-49bd-96f1-9bdf7aed52bb" />

**Comment by PhillipVas** [comment]
Just had this on 2.60.1 (2.60.2 not available for me). It was using 600GB of ram. If it happens again i'll try the logging build

**Comment by Josscii** [comment]
same for 2.60.2

<img width="366" height="38" alt="Image" src="https://github.com/user-attachments/assets/bab7f516-8613-4052-96fc-90908c2c565d" />

**Comment by DanPristupov** [comment]
No one sent me a log, so I fixed the problem at random and released 2.60.4. Most likely, it hides the problem rather than solves it.

**Comment by Josscii** [comment]
@DanPristupov Had installed the log version, will upload the log if reproduce the problem.

**Comment by Rspoon3** [comment]
`richardwitherspoon@rwitherspoon-MacBook-Pro /Applications % head -n 3 ~/Library/Application\ Support/com.DanPristupov.Fork/repositories.toml
source_dirs = ["/Users/richardwitherspoon/"]
scan_depth = 5
ignore = []
`

This is after upgrading to 2.60.4
