### ISSUE TITLE
Add a one-step way to add a fixup commit

### ISSUE THREAD

**Issue by YesThatAllen** [ForkIssues/Tracker#275]
Building off of #41 in which we are shown a way to turn a commit into a fixup.

I looked all over for a way to create a commit that is a fixup, and didn't see it (only an amend option)

Because it's easier just to create the fixup vs commit & start a rebase, I'd love to see an option which is:

`git commit --fixup HEAD`

Thanks for making Fork, it's been a joy to use so far, and this would make it even nicer.

**Comment by DanPristupov** [comment]
Can that be solved with Custom Actions? https://github.com/ForkIssues/Tracker/issues/123

**Comment by laurentvaills** [comment]
I would actually really love to add that "fixup" checkbox when I want to commit, and then being able to choose to which commit I want to refer for this fixup. This is one of the last steps I am still doing on plain command line, because I can't do it with Fork.

**Comment by vassilevsky** [comment]
Added as a custom action as well. Just like in SourceTree LOL :D Still would be cool to have it out of the box, in a commit context menu.

**Comment by tobiastom** [comment]
Also solved it with custom command, but I agree that a stock again would be nice.

**Comment by wvreeven** [comment]
Apparently this issue still is open. I just requested this to Dan via email and his reply was "I'd like to keep the UI clean" which I think is ridiculous. Good to know I am not the only one that is looking for this feature. Please implement this as requested!

**Comment by jamescrowley** [comment]
In case it's useful to others, the following custom action worked well for me. It applies the current staged files as a fixup to the selected commit. Choose the "visible in the commit context menu" option, and a UI bash command:

<img width="404" height="119" alt="Image" src="https://github.com/user-attachments/assets/c04d7892-8f52-4baf-9dfb-d4f4fa0cd95b" />

```
git commit --fixup=${sha}
GIT_SEQUENCE_EDITOR=: GIT_EDITOR=: git rebase -i --autosquash $(git rev-parse ${sha}^)
```

**Comment by Tensho** [comment]
UI component for the commit `--fixup` (and `--no-verify`) is highly appreciated.
